import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "./useAuth";
import type { Artifact } from "./useArtifacts";
import type { PipelineRun, PipelineStepResult } from "./useAgentPipelines";

export interface ArtifactWithLineage extends Artifact {
  pipelineRunId?: string;
  pipelineName?: string;
  generatedAt?: string;
}

export interface LineageNode {
  id: string;
  type: "pipeline_run" | "artifact";
  data: {
    pipelineRun?: PipelineRun;
    artifact?: ArtifactWithLineage;
  };
}

export interface LineageEdge {
  id: string;
  source: string;
  target: string;
  label?: string;
}

export interface LineageData {
  nodes: LineageNode[];
  edges: LineageEdge[];
  pipelineRuns: PipelineRun[];
  artifacts: ArtifactWithLineage[];
}

export function useArtifactLineage(projectId?: string, workspaceId?: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ["artifact-lineage", projectId, workspaceId],
    queryFn: async (): Promise<LineageData> => {
      if (!workspaceId) {
        return { nodes: [], edges: [], pipelineRuns: [], artifacts: [] };
      }

      // Fetch pipeline runs
      let runsQuery = supabase
        .from("pipeline_runs")
        .select("*, pipeline:agent_pipelines(*)")
        .eq("workspace_id", workspaceId);

      if (projectId) {
        runsQuery = runsQuery.or(`project_id.eq.${projectId},project_id.is.null`);
      }

      const { data: runsData, error: runsError } = await runsQuery
        .order("created_at", { ascending: false })
        .limit(100);

      if (runsError) throw runsError;

      // Fetch artifacts
      let artifactsQuery = supabase
        .from("artifacts")
        .select("*")
        .eq("workspace_id", workspaceId)
        .neq("status", "ARCHIVED");

      if (projectId) {
        artifactsQuery = artifactsQuery.eq("project_id", projectId);
      }

      const { data: artifactsData, error: artifactsError } = await artifactsQuery
        .order("created_at", { ascending: false });

      if (artifactsError) throw artifactsError;

      // Process pipeline runs
      const pipelineRuns: PipelineRun[] = (runsData || []).map(r => ({
        ...r,
        status: r.status as PipelineRun["status"],
        step_results: (r.step_results as unknown as PipelineStepResult[]) || [],
        pipeline: r.pipeline ? {
          ...r.pipeline,
          steps: (r.pipeline.steps as unknown as any[]) || []
        } : undefined
      }));

      // Process artifacts and identify those generated by pipelines
      const artifacts: ArtifactWithLineage[] = (artifactsData || []).map(a => {
        const contentJson = a.content_json as Record<string, any> || {};
        return {
          ...a,
          tags: a.tags || [],
          labels: a.labels as Record<string, any> || {},
          content_json: contentJson,
          pipelineRunId: contentJson.pipelineRunId,
          pipelineName: contentJson.pipelineName,
          generatedAt: contentJson.generatedAt,
        } as ArtifactWithLineage;
      });

      // Build lineage graph
      const nodes: LineageNode[] = [];
      const edges: LineageEdge[] = [];
      const addedNodeIds = new Set<string>();

      // Add pipeline runs as nodes
      pipelineRuns.forEach(run => {
        if (run.status === "completed") {
          const nodeId = `run-${run.id}`;
          if (!addedNodeIds.has(nodeId)) {
            nodes.push({
              id: nodeId,
              type: "pipeline_run",
              data: { pipelineRun: run }
            });
            addedNodeIds.add(nodeId);
          }
        }
      });

      // Add artifacts as nodes and create edges
      artifacts.forEach(artifact => {
        const artifactNodeId = `artifact-${artifact.id}`;
        if (!addedNodeIds.has(artifactNodeId)) {
          nodes.push({
            id: artifactNodeId,
            type: "artifact",
            data: { artifact }
          });
          addedNodeIds.add(artifactNodeId);
        }

        // If artifact was generated by a pipeline run, create an edge
        if (artifact.pipelineRunId) {
          const runNodeId = `run-${artifact.pipelineRunId}`;
          if (addedNodeIds.has(runNodeId)) {
            edges.push({
              id: `edge-${artifact.pipelineRunId}-${artifact.id}`,
              source: runNodeId,
              target: artifactNodeId,
              label: "generated"
            });
          }
        }
      });

      return {
        nodes,
        edges,
        pipelineRuns,
        artifacts
      };
    },
    enabled: !!user && !!workspaceId,
  });
}

// Get artifacts generated by a specific pipeline run
export function useArtifactsFromPipelineRun(pipelineRunId?: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ["artifacts-from-pipeline", pipelineRunId],
    queryFn: async () => {
      if (!pipelineRunId) return [];

      const { data, error } = await supabase
        .from("artifacts")
        .select("*")
        .neq("status", "ARCHIVED");

      if (error) throw error;

      // Filter artifacts that were generated by this pipeline run
      return (data || []).filter(a => {
        const contentJson = a.content_json as Record<string, any> || {};
        return contentJson.pipelineRunId === pipelineRunId;
      }).map(a => ({
        ...a,
        tags: a.tags || [],
        labels: a.labels as Record<string, any> || {},
        content_json: a.content_json as Record<string, any> || {},
      })) as Artifact[];
    },
    enabled: !!user && !!pipelineRunId,
  });
}

// Get pipeline run that generated a specific artifact
export function usePipelineRunForArtifact(artifactId?: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ["pipeline-run-for-artifact", artifactId],
    queryFn: async () => {
      if (!artifactId) return null;

      // First get the artifact to find the pipeline run ID
      const { data: artifact, error: artifactError } = await supabase
        .from("artifacts")
        .select("*")
        .eq("id", artifactId)
        .maybeSingle();

      if (artifactError) throw artifactError;
      if (!artifact) return null;

      const contentJson = artifact.content_json as Record<string, any> || {};
      const pipelineRunId = contentJson.pipelineRunId;

      if (!pipelineRunId) return null;

      // Get the pipeline run
      const { data: run, error: runError } = await supabase
        .from("pipeline_runs")
        .select("*, pipeline:agent_pipelines(*)")
        .eq("id", pipelineRunId)
        .maybeSingle();

      if (runError) throw runError;
      if (!run) return null;

      return {
        ...run,
        step_results: (run.step_results as unknown as PipelineStepResult[]) || [],
        pipeline: run.pipeline ? {
          ...run.pipeline,
          steps: (run.pipeline.steps as unknown as any[]) || []
        } : undefined
      } as PipelineRun;
    },
    enabled: !!user && !!artifactId,
  });
}
